name: SmartShop WhatsApp Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install node-fetch
        run: npm install node-fetch@2

      - name: Start Bot
        env:
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
        run: node index.js
